### ISSUE TITLE
ludwich need help - kanji sign

### ISSUE THREAD

**Issue by ludwich66** [840922704/BLE_DMM_Client#5]
Hi Chengbo,

i need your help. I translate a User Manual for RC3563 Battery Tester.
I can't find UTF8 code for the last Kanji Sign. 
can you help me with that?

<img width="245" alt="image" src="https://user-images.githubusercontent.com/12202733/192792948-5b0ede56-6fc8-4243-a066-44f1dec24878.png">

https://github.com/ludwich66/RC3563/wiki

Greatings Ludwich

**Comment by 840922704** [comment]
Glad to help~
校准电阻
Is that what you need?

**Comment by ludwich66** [comment]
Yepp !!! idid not find last Sign
What did it meen? is it separat readable?
Kanji isnt complete unreadable for me ;-(

Tanks Ludwich

> Am 28.09.2022 um 15:57 schrieb Chengbo Zhao ***@***.***>:
> 
> 阻

**Comment by ludwich66** [comment]
You did It !!

**Comment by 840922704** [comment]
电阻 resistance
Maybe you need an OCR software  ;-)

**Comment by ludwich66** [comment]
I used this UTF8 page - an found all other Sign…
> 
> https://www.khngai.com/chinese/charmap/tbluni.php?page=5 <https://www.khngai.com/chinese/charmap/tbluni.php?page=5>
How do you write in Kanji with an normal PC Keyboard ?
Questions over Questions ;-)

Ludwich

**Comment by 840922704** [comment]
In primary school, almost everyone has a dictionary called 新华字典. If we can't read and speak one character, we find it by Radical and Indexing component & the number of strokes.
For example, as for 阻, we index it by 阝(2 strokes), then the number of the rest of the strokes - 5. Then we find '阻'. And we can learn the Chinese phonetic alphabets (Pinyin) is 'zu'. Then we type 'zu' and find '阻' using Pinyin IME.
As we can speak almost all the characters, type 'zu' and find '阻' using Pinyin IME is the only thing we do. It's very fast that we can type 'dz' rather than 'dianzu' for '电阻'.
Another simpler method, usually used by elder (especially using phone), is handwriting recognize function in Pinyin IME.

**Comment by ludwich66** [comment]
太好了，即使我不明白阻值如何
得到计数器 2 / 5。 第一个标志很清楚，但第二个，壁橱？ 6 笔笔触或 4 笔用于大圆弧。
复杂

;-)
谢谢你的详细回答

问候路德维希

> Am 28.09.2022 um 16:55 schrieb Chengbo Zhao ***@***.***>:
> 
> In primary school, almost everyone has a dictionary called 新华字典. If we can't read and speak one character, we find it by Radical and Indexing component & the number of strokes.
> For example, as for 阻, we index it by 阝(2 strokes), then the number of the rest of the strokes - 5. Then we find 阻. And we can learn the Chinese phonetic alphabets (Pinyin) is . Then we type and find <阻> using Pinyin IME.
> As we can speak almost all the characters, type and find <阻> using Pinyin IME is the only thing we do. It's very fast that we can type rather than for <电阻>.
> Another simpler method, usually used by elder (especially using phone), is handwriting recognize function in Pinyin IME.
